#!/bin/bash

echo "=== Інструкція по налаштуванню jbot.khpcc.com на Raspberry Pi ==="
echo ""

echo "КРОК 1: Налаштування DNS"
echo "----------------------------------------"
echo "Зайдіть в панель управління вашого DNS провайдера (де зареєстрований khpcc.com)"
echo "Додайте A-запис:"
echo "  Type: A"
echo "  Name: jbot"
echo "  Value: [IP адреса вашого Raspberry Pi]"
echo "  TTL: 3600"
echo ""
echo "Перевірте DNS командою (на Raspberry Pi):"
echo "  nslookup jbot.khpcc.com"
echo ""

echo "КРОК 2: Скопіюйте файл nginx-jbot.conf на Raspberry Pi"
echo "----------------------------------------"
echo "На вашому комп'ютері:"
echo "  scp nginx-jbot.conf pi@[IP_RASPBERRY_PI]:/tmp/"
echo ""
echo "На Raspberry Pi:"
echo "  sudo cp /tmp/nginx-jbot.conf /etc/nginx/sites-available/jbot.khpcc.com"
echo "  або"
echo "  sudo cp /tmp/nginx-jbot.conf /etc/nginx/conf.d/jbot.khpcc.com.conf"
echo ""

echo "КРОК 3: Перевірте, що Docker контейнер працює"
echo "----------------------------------------"
echo "На Raspberry Pi виконайте:"
echo "  docker ps"
echo "  curl http://localhost:8081"
echo ""
echo "Якщо контейнер не запущений:"
echo "  cd /шлях/до/проекту"
echo "  docker-compose up -d"
echo ""

echo "КРОК 4: Отримайте SSL сертифікат"
echo "----------------------------------------"
echo "На Raspberry Pi виконайте:"
echo "  sudo apt update"
echo "  sudo apt install certbot python3-certbot-nginx -y"
echo "  sudo certbot --nginx -d jbot.khpcc.com"
echo ""
echo "Certbot автоматично налаштує SSL в конфігурації Nginx"
echo ""

echo "КРОК 5: Активуйте конфігурацію Nginx"
echo "----------------------------------------"
echo "Якщо використовуєте sites-available/sites-enabled:"
echo "  sudo ln -s /etc/nginx/sites-available/jbot.khpcc.com /etc/nginx/sites-enabled/"
echo ""
echo "Перевірте конфігурацію:"
echo "  sudo nginx -t"
echo ""
echo "Перезапустіть Nginx:"
echo "  sudo systemctl restart nginx"
echo ""

echo "КРОК 6: Перевірка"
echo "----------------------------------------"
echo "Відкрийте в браузері:"
echo "  https://jbot.khpcc.com"
echo ""
echo "Або з командного рядка:"
echo "  curl https://jbot.khpcc.com"
echo ""

echo "=== Діагностика проблем ==="
echo "----------------------------------------"
echo "Якщо не працює, перевірте:"
echo ""
echo "1. DNS налаштований:"
echo "   nslookup jbot.khpcc.com"
echo ""
echo "2. Nginx працює:"
echo "   sudo systemctl status nginx"
echo ""
echo "3. Docker контейнер працює:"
echo "   docker ps"
echo "   docker logs [CONTAINER_ID]"
echo ""
echo "4. Порт 8081 відповідає:"
echo "   curl http://localhost:8081"
echo ""
echo "5. Nginx логи:"
echo "   sudo tail -f /var/log/nginx/jbot_error.log"
echo "   sudo tail -f /var/log/nginx/jbot_access.log"
echo ""
echo "6. Firewall відкритий:"
echo "   sudo ufw status"
echo "   sudo ufw allow 80/tcp"
echo "   sudo ufw allow 443/tcp"
echo ""
